import './globals.css'
import { Inter } from 'next/font/google'
import Header from './components/header/header';

<link href="https://fonts.googleapis.com/css2?family=Noto+Naskh+Arabic:wght@400;500&family=Nunito+Sans&display=swap" rel="stylesheet"></link>


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">      
      <body className={inter.className}>
           <Header />
           {children}
        </body>
    </html>
  )
}
